{
 "title": "K8s Load Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "label_values(iperf3_metric{metric=\"bits_per_second_streams_term_0\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "byte_streams (in Byte)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "iperf3_metric{metric=~\".*bytes_streams_term_*.\", name=\"${name}\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "RTT (in ms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iperf3_metric{metric=~\".*rtt_streams_term_*.\", name=\"${name}\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "TCP RetransMission (in Byte)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "iperf3_metric{metric=~\".*retransmits_streams_term_*.\", name=\"${name}\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Send Congestion Window (in Byte)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "iperf3_metric{metric=~\".*sndcwd_streams_term_*.\", name=\"${name}\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "TCP Send Window (in Byte)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iperf3_metric{metric=~\".*sndwnd_streams_term_*.\", name=\"${name}\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  }
 ]
}